# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOiEUa_0uhiKGPo7Ec24UZl8HaR-vp8C
"""



"""Example of Addition"""

A = 2
B = 3
C = A+B
print(C)

"""Example of a String"""

Greetings= "What up doctor"
print (Greetings)